### PR TITLE
No notifications after reconnecting

### PR DESCRIPTION
**Pull request by gharlan**
After reconnecting to internet (e. g. after standby mode) no notifications are triggered.

Updating Pusher framework will fix it.

PS: Are you interested in an implementation of this approach: https://github.com/lukeredpath/libPusher#handling-network-connectivity-errors-and-disconnects?
At first I thought this would fix the bug and I implemented it, so I could open a pull request if you want. But to fix the bug, it isn't necessary.

### CODE REVIEW

**Comment by joshk** [comment]
Hi @gharlan,

Any and all help fixing bugs and updating deps would be awesome.

If you send me a PR I will merge and give you commit rights :)

<3<3<3

Josh

**Comment by sarahhodne** [comment]
Like @joshk said, if you can submit a PR for the bug that would be A+, and if you already have Reachability implemented, a PR for that too would be great.

**Comment by gharlan** [comment]
(added commit)

**Comment by joshk** [comment]
@dvyjones I'll let you merge and test :)

**Pull request merged**
