### PR TITLE
implemented reachability observer

### PR DESCRIPTION
**Pull request by gharlan**

### CODE REVIEW

**Comment by joshk** [comment]
hey @gharlan,

How does this work?

Thanks,

Josh

**Comment by gharlan** [comment]
hi @joshk 

look here: https://github.com/lukeredpath/libPusher#handling-network-connectivity-errors-and-disconnects
Does this answer your question?

gregor

**Comment by joshk** [comment]
Sorry, small question, this PR updated the pusher lib, but did anything need to be added to Travis Toolbar to support reachability?

**Comment by sarahhodne** [comment]
Depends on what you want to do with it. Right now it'll just try to reconnect if it detects that it loses the connection. Check `PusherConnection.m` for the code, mostly `-[PusherConnection reachabilityChanged:]`.

**Pull request merged**
