### PR TITLE
Base

### PR DESCRIPTION
**Pull request by phoet**
hey josh,

i implemented some of the ui elements, but i am not quite sure which pusher events are interesting for users, especially if one is building an application with several rubies. this might get a little confusing.

bye

### CODE REVIEW

**Comment by Overbryd** [comment]
I'll have a look at it and will update here by the end of this week.
Update: Just don't get me wrong. I'm looking into this, because I'm interested in it. Sorry for the possible confusion I caused commenting on this.

**Comment by phoet** [comment]
cool!

**Comment by Overbryd** [comment]
@phoet this code looks nice. But I ask myself to where this pull request should go. The `travis-watcher-macosx` project is basically what you are doing with `TravisSeeEye`. My guess is that `TravisSeeEye` is the maintained one.

I would take portions of the code from this pull request and use it in `TravisSeeEye`.
Another thing: Do you have any hint how to manually trigger Pushr events? I would like to play around a bit more, but I have never used Pushr.

@joshk: What do you think? This pull request is nice, but this repository here seems abandoned (no pun intended).
I am currently interested in MacRuby programming and will contribute some time to `TravisSeeEye`. My goal no bigger than to bring TravisSeeEye to the App Store. What do you think of concentrating efforts on TravisSeeEye side?

**Comment by phoet** [comment]
@Overbryd you are probably right. this pull request was done after chatting a little bit about what @joshk was thinking that such an app should do, but we never really got it going. since i did not work with Pushr neither, and the TravisSeeEye app already did it's job quite well i did not push on this any more.

**Comment by joshk** [comment]
Hey @Overbryd and @phoet 

I feel embarrassed that I have not replied to this issue sooner, it got lost in my inbox, I am sorry.

@phoet I love what you did with TravisSeeEye and would love to work on it with you to make it even more awesome. This repo had good intentions but Travis development eventually kept me too busy, and my mac skills were to slow to evolve.

Would you be interested it brainstorming how we can make this even better?

<3<3<3

Josh

**Comment by phoet** [comment]
is any of you on railsberry next week? we could have a talk there then.

**Comment by joshk** [comment]
I will be at Railsberry, I'll be speaking on the second day.

Lets find a time to sit down and talk about how to make this super awesome! :)

**Comment by phoet** [comment]
(while having a beer)

**Comment by joshk** [comment]
I won't say no to that ;)

**Comment by sarahhodne** [comment]
We just switched to Objective-C, so this doesn't really apply that much anymore. Closing this, but feel free to resubmit as Objective-C.

**Comment by sarahhodne** [comment]
A lot of this is now implemented in the Objective-C version.

**Pull request closed without merging**
