### PR TITLE
add click event for growl notifications

### PR DESCRIPTION
**Pull request by gharlan**
the click event opens the build URL in browser

### CODE REVIEW

**Comment by joshk** [comment]
AWESOME!

MERGE IT @dvyjones !!!

**Comment by sarahhodne** [comment]
@joshk Sorry, but I've been crazy busy the last few days. I'm leaving for England in a few hours, but I promise to look at this when I get back in two weeks. Same applies to all other issues in mentioned in.

**Comment by joshk** [comment]
LEAVING FOR ENGLAND? ON A HOLIDAY? TRAVIS SHOULD BE YOUR HOLIDAY! ;)

**Comment by joshk** [comment]
@henrikhodne CAN WE MERGE THIS AWESOMENESS?

**Comment by sarahhodne** [comment]
Sorry, yes. LGTM.

**Pull request merged**
